spring:
  thymeleaf:
    prefix: file:///${user.dir}//target//classes//static/
  data:
    mongodb:
      auto-index-creation: true
  profiles:
    active: dev
mongock:
  change-logs-scan-package: com.telelogx.chatbot.model.databaseChangeLog